<?xml version="1.0" encoding="ASCII"?>

<!-- oks-schema version 2.2 -->


<!DOCTYPE oks-schema [
  <!ELEMENT oks-schema (info, (include)?, (comments)?, (class)+)>
  <!ELEMENT info EMPTY>
  <!ATTLIST info
      name CDATA #IMPLIED
      type CDATA #IMPLIED
      num-of-items CDATA #REQUIRED
      oks-format CDATA #FIXED "schema"
      oks-version CDATA #REQUIRED
      created-by CDATA #IMPLIED
      created-on CDATA #IMPLIED
      creation-time CDATA #IMPLIED
      last-modified-by CDATA #IMPLIED
      last-modified-on CDATA #IMPLIED
      last-modification-time CDATA #IMPLIED
  >
  <!ELEMENT include (file)+>
  <!ELEMENT file EMPTY>
  <!ATTLIST file
      path CDATA #REQUIRED
  >
  <!ELEMENT comments (comment)+>
  <!ELEMENT comment EMPTY>
  <!ATTLIST comment
      creation-time CDATA #REQUIRED
      created-by CDATA #REQUIRED
      created-on CDATA #REQUIRED
      author CDATA #REQUIRED
      text CDATA #REQUIRED
  >
  <!ELEMENT class (superclass | attribute | relationship | method)*>
  <!ATTLIST class
      name CDATA #REQUIRED
      description CDATA ""
      is-abstract (yes|no) "no"
  >
  <!ELEMENT superclass EMPTY>
  <!ATTLIST superclass name CDATA #REQUIRED>
  <!ELEMENT attribute EMPTY>
  <!ATTLIST attribute
      name CDATA #REQUIRED
      description CDATA ""
      type (bool|s8|u8|s16|u16|s32|u32|s64|u64|float|double|date|time|string|uid|enum|class) #REQUIRED
      range CDATA ""
      format (dec|hex|oct) "dec"
      is-multi-value (yes|no) "no"
      init-value CDATA ""
      is-not-null (yes|no) "no"
      ordered (yes|no) "no"
  >
  <!ELEMENT relationship EMPTY>
  <!ATTLIST relationship
      name CDATA #REQUIRED
      description CDATA ""
      class-type CDATA #REQUIRED
      low-cc (zero|one) #REQUIRED
      high-cc (one|many) #REQUIRED
      is-composite (yes|no) "no" 
      is-exclusive (yes|no) "no" 
      is-dependent (yes|no) "no" 
      ordered (yes|no) "no"
  >
  <!ELEMENT method (method-implementation*)>
  <!ATTLIST method
      name CDATA #REQUIRED
      description CDATA ""
  >
  <!ELEMENT method-implementation EMPTY>
  <!ATTLIST method-implementation
      language CDATA #REQUIRED
      prototype CDATA #REQUIRED
      body CDATA ""
  >
]>

<oks-schema>

<info name="" type="" num-of-items="3" oks-format="schema" oks-version="862f2957270" created-by="jcfree" created-on="mu2edaq13.fnal.gov" creation-time="20230123T223700" last-modified-by="jcfree" last-modified-on="mu2edaq13.fnal.gov" last-modification-time="20230123T223700"/> 

 <class name="BaseConfParams" description="A software executable" is-abstract="no">
  <attribute name="device_str" description="Name of device" type="string" init-value="Unknown" is-not-null="yes"/>
  <attribute name="hardware_state_recovery_enabled" type="bool" init-value="true"/>
  <attribute name="timing_session_name" type="string" init-value=" "/>
 </class>

 <class name="TimingEndpointController" description="An executable which reads out subdetectors">
  <superclass name="BaseConfParams"/>
  <attribute name="device_str" description="Name of device" type="string"/>
  <attribute name="hardware_state_recovery_enabled" type="bool" init-value="true"/>
  <attribute name="timing_session_name" type="string" init-value="Unknown"/>
  <attribute name="endpoint_id" type="u32" init-value="true"/>
  <attribute name="address" type="u32" init-value="Unknown"/>
  <attribute name="parition" type="u32" init-value="Unknown"/>
 </class>

 <class name="TimingMasterController" description="An executable which reads out subdetectors">
  <superclass name="BaseConfParams"/>
  <attribute name="device_str" description="Name of device" type="string"/>
  <attribute name="hardware_state_recovery_enabled" type="bool" init-value="true"/>
  <attribute name="timing_session_name" type="string" init-value="Unknown"/>
  <attribute name="endpoint_scan_period" type="u32" init-value="0"/>
  <attribute name="clock_config" type="string" init-value="Unknown"/>
  <attribute name="soft" type="bool" init-value="false"/>
  <attribute name="fanout_mode" type="string" init-value="Unknown"/>
  <attribute name="monitored_endpoints" type="string" init-value="Unknown"/>
 </class>

 <class name="TimingPartitionController" description="An executable which reads out subdetectors">
  <superclass name="BaseConfParams"/>
  <attribute name="device_str" description="Name of device" type="string"/>
  <attribute name="hardware_state_recovery_enabled" type="bool" init-value="true"/>
  <attribute name="timing_session_name" type="string" init-value="Unknown"/>
  <attribute name="parition_id" type="u32" init-value="0"/>
  <attribute name="trigger_mask" type="u32" init-value="Unknown"/>
  <attribute name="spill_gate_enabled" type="bool" init-value="false"/>
  <attribute name="rate_control_enabled" type="bool" init-value="false"/>
</class>
  
<class name="TimingFanoutController" description="An executable which reads out subdetectors">
 <superclass name="BaseConfParams"/>
 <attribute name="device_str" description="Name of device" type="string"/>
 <attribute name="hardware_state_recovery_enabled" type="bool" init-value="true"/>
 <attribute name="timing_session_name" type="string" init-value="Unknown"/>
 <attribute name="clock_config" type="string" init-value="Unknown"/>
</class>
    
</oks-schema>
